### ISSUE TITLE
Error setting TTL index on collection / Cannot determine state of server

### ISSUE THREAD

**Issue by davisford** [diversario/connect-mongostore#26]
[I came here from this thread](https://github.com/kcbanner/connect-mongo/issues/65)

I do have a replica set in production, so I decided it would be better to use this module, and I thought maybe this issue would disappear if I pass it the mongoose connection, instead of trying to spawn a new connection to the database, but alas, I am still seeing this get thrown on [livereload](https://www.npmjs.org/package/gulp-livereload) trigger of app restart:

```
Error: Error getting collection: sessions <Error: Error setting TTL index on collection : sessions <Error: Error setting TTL index on collection : sessions <Error: Cannot determine state of server>>>
   at /Users/davis/git/warehouse-web/node_modules/connect-mongostore/lib/connect-mongostore.js:110:22
   at Db.collection (/Users/davis/git/warehouse-web/node_modules/connect-mongostore/node_modules/mongodb/lib/mongodb/db.js:534:27)
   at MongoStore.getCollection (/Users/davis/git/warehouse-web/node_modules/connect-mongostore/lib/connect-mongostore.js:109:13)
   at MongoStore.get (/Users/davis/git/warehouse-web/node_modules/connect-mongostore/lib/connect-mongostore.js:133:10)
   at session (/Users/davis/git/warehouse-web/node_modules/express-session/index.js:355:11)
   at Layer.handle [as handle_request] (/Users/davis/git/warehouse-web/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/Users/davis/git/warehouse-web/node_modules/express/lib/router/index.js:270:13)
   at /Users/davis/git/warehouse-web/node_modules/express/lib/router/index.js:237:9
   at Function.proto.process_params (/Users/davis/git/warehouse-web/node_modules/express/lib/router/index.js:312:12)
   at /Users/davis/git/warehouse-web/node_modules/express/lib/router/index.js:228:12
```

Here's what I'm doing -- please tell me if there is a recommended way to resolve this:

in app.js

``` javascript
mongoose.connect(config.mongo.uri, config.mongo.options);

var app = express();

mongoos.connection.on('connected', function () {
  debug('mongoose connected to %s, mongoose.connection.readyState %d', config.mongo.uri, mongoose.connection.readyState);

  // other modules are required here like mongoose models 

  // this require is now delayed until supposedly mongoose is in ready state
  require('./routes/express')(app);
});

mongoose.connection.on('error', function (err) { console.error('mongoose connection error ', err); });
```

in ./routes/express.js (required from above)

``` javascript
var session = require('express-session'),
  MongoStore = require('connect-mongostore')(session)

module.exports = function (app) {

   // other code setup up cookie parser, body parser, etc.
  app.use(session({
    secret: secret,
    saveUninitialized: true,
    resave: true,
    store: new MongoStore({
      mongooseConnection: mongoose.connections[0],
      collection: 'session',
      auto_reconnect: true
  }, function () {
      debug('express connect-mongostore session store connected.');
  }));
```

My localhost dev machine does not have a replica set -- not that it matters much for this issue.  The problem happens when livereload triggers a server reload.  I'm using gulp-livereload, and when it detects a file has been saved in the server source, it will respawn the app.

``` javascript
// have nodemon start the express server; nodemon only restarts on change in src/server
gulp.task('nodemon', function () {
  plugins.nodemon({
    script: './src/server/bin/www',
    verbose: true,
    env: {
      'NODE_ENV': 'development',
      'DEBUG': '* -express:* -send -session -mquery -express-session'
    },
    watch: './src/server',
    ext: 'js jade html css styl json',
    nodeArgs: ['--debug']
  }).on('restart', function () {
    // initiate livereload -- sometimes happens too fast; 500 ms was too short for me
    setTimeout(function () {
      log('Trying to refresh livereload after server has restarted...');
      reload.changed('/');
    }, 1000);
  });
});
```

**Comment by davisford** [comment]
Ok, I did resolve it this way -- this seems to be the key piece that fixes it:

``` javascript
mongoose.connect.on('connected', function () {
   var server = app.listen(app.get('port')), function () { 
     debug('Express server listening on port %d in mode %s', server.address().port, app.get('env'));
  });
});
```

The call to `app.listen` must be delayed until the mongoose connection is ready.

**Comment by diversario** [comment]
Thanks for posting the resolution! It makes sense, even if not very convenient. I'll add a note to README about Mongoose connection for future reference.

**Comment by davisford** [comment]
Hey @diversario have you had any luck using replica sets with mongoose?  I can't seem to get it to work.  See my comment here: https://github.com/LearnBoost/mongoose/issues/2089#issuecomment-59854430

Let me know if you have any clues as to what might be going on.

**Comment by diversario** [comment]
I have not. When I used MongoDB I used it with mongodb native. There is someone [here](https://github.com/diversario/connect-mongostore/issues/23) who's using it, maybe you could ask them?
